### ISSUE TITLE
Unable to Install Apps

### ISSUE THREAD

**Issue by jlandes** [quanglam2807/appifier#221]
When attempting to install any app in WebCatalog, I receive an error message that the app cannot be installed. I'm running 8.0.3 on Linux Mint 18.3 x64.

![webcatalog](https://user-images.githubusercontent.com/34172050/33502361-bb365d2a-d6ad-11e7-87de-ec992d7d4586.png)

**Comment by demicon** [comment]
Im getting the same error
`Error: Forked script error`
`at ChildProcess.child.on (/opt/WebCatalog/resources/app/build/libs/install-app-async/index.js:56:18)`
`at emitTwo (events.js:106:13)`
`at ChildProcess.emit (events.js:194:7)`
`at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)`
`actions.js:47 Error: Installing failed.`
`at EventEmitter.o (install-app-async.js:23)`
`at emitThree (events.js:121)`
`at EventEmitter.emit (events.js:197)`

OS: Elementary os 0.4.1 Loki, x64
Webcatalog version: 8.0.3

**Comment by quanglam2807** [comment]
@jlandes @demicon @younglee327 @ichowise @matrixik @rosiered999

Can you guys download v8.0.4: https://github.com/webcatalog/webcatalog/releases/tag/v8.0.4, try to install an app and then send me the log, please? Also, please include what OS you are using together with the log.

**Comment by fsdias** [comment]
I am on ubuntu 16.04 and run webcatalog 8.0.3 from the commandline. This is the error:

Error: /lib/x86_64-linux-gnu/libz.so.1: version `ZLIB_1.2.9' not found (required by /opt/WebCatalog/resources/app/node_modules/sharp/build/Release/../../vendor/lib/libpng16.so.16)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/WebCatalog/resources/app/node_modules/sharp/lib/constructor.js:9:15)
    at Object.<anonymous> (/opt/WebCatalog/resources/app/node_modules/sharp/lib/constructor.js:234:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)

**Comment by quanglam2807** [comment]
@fsdias Related to lovell/sharp#892. I'm looking for an alternative.

**Comment by demicon** [comment]
OS: Windows 10 x64
Webcatalog 8.0.4
Apps installed successfully. No errors are seen in log.
![image](https://user-images.githubusercontent.com/26656849/33622385-b1e58782-da13-11e7-9e3b-d81ef7f43376.png)
I am yet to try it in linux

**Comment by nyex** [comment]
Mine seems to be a timeout issue due to slow internet connection. Should I report a new bug?

Ubuntu 17.10
WebCatalog 8.0.4

Stuck here:

Downloading tmp-8091-0-electron-v1.7.9-linux-x64.zip
Error: read ECONNRESET
Downloading tmp-8282-0-electron-v1.7.9-linux-x64.zip
[=>                                           ] 6.0% of 51.24 MB (32 kB/s)

.... and so on and so forth.

**Comment by demicon** [comment]
Installed Webcatalog 8.0.4 using .deb
Ubuntu 16.04.3 x64
It keeps on showing installing but never getting installed
![image](https://user-images.githubusercontent.com/26656849/33633047-918eb00e-da35-11e7-9f04-aa9a6728c7ef.png)

**Comment by quanglam2807** [comment]
@nyex `electron` is supposed to be pre-downloaded & included in the package. I'll have a look.

@demicon @fsdias Please test v8.0.5 on Linux: https://github.com/webcatalog/webcatalog/releases/tag/v8.0.5

**Comment by grey-dev-0** [comment]
@quanglam2807 It seems you've managed to fix the problem in 8.0.5.
Thank you for this great app.

**Comment by matrixik** [comment]
```
Windows 8.1 Enterprise
WebCatalog Version 8.0.5
electron: 1.7.9
chrome: 58.0.3029.110
v8: 5.8.283.38
node: 7.9.0
```
When creating custom app (with local PNG file):
```
Error: connect ETIMEDOUT 192.30.253.112:443
    at Object.exports._errnoException (util.js:1050)
    at exports._exceptionWithHostPort (util.js:1073)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097)
```
When trying to install Trello from directory:
```
Error: ENOTEMPTY: directory not empty, rmdir 'C:\Users\ZybortD\AppData\Local\Temp\tmp-4504VuJdLLTsfT8T'
    at Object.fs.rmdirSync (fs.js:856:18)
    at _rmdirRecursiveSync (C:\Users\ZybortD\AppData\Local\Programs\WebCatalog\resources\app\node_modules\tmp\lib\tmp.js:314:10)
    at Object._cleanupCallback [as cleanupCallback] (C:\Users\ZybortD\AppData\Local\Programs\WebCatalog\resources\app\node_modules\tmp\lib\tmp.js:446:7)
    at RedirectableRequest.req.on (C:\Users\ZybortD\AppData\Local\Programs\WebCatalog\resources\app\build\libs\install-app-async\script.js:56:20)
    at emitOne (events.js:96:13)
    at RedirectableRequest.emit (events.js:191:7)
    at ClientRequest.eventHandlers.(anonymous function) (C:\Users\ZybortD\AppData\Local\Programs\WebCatalog\resources\app\node_modules\follow-redirects\index.js:22:22)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:191:7)
    at TLSSocket.socketErrorListener (_http_client.js:358:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:191:7)
    at emitErrorNT (net.js:1283:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
actions.js:47 Error: Installing failed.
    at EventEmitter.o (install-app-async.js:23)
    at emitThree (events.js:121)
    at EventEmitter.emit (events.js:197)
```

**Comment by fsdias** [comment]
It's also working on Ubuntu 16.04. Thanks a lot

**Comment by quanglam2807** [comment]
@grey-dev-0 @fsdias Awesome! Thanks a lot for letting me know.

@matrixik I'm working on a fix :)

**Comment by quanglam2807** [comment]
@matrixik Can you test https://github.com/webcatalog/webcatalog/releases/tag/v8.0.6

**Comment by matrixik** [comment]
With 8.0.6 I have no error but still I can't install app in any way, it just showing "INSTALLING" with moving blue bar. I started installing yesterday so looks like it doesn't have any timeout set.

**Comment by quanglam2807** [comment]
@matrixik My bad! It was a bad build. Please try: https://github.com/webcatalog/webcatalog/releases/tag/v8.0.7

**Comment by jlandes** [comment]
@quanglam2807 It seems to be working fine for me now.

**Comment by matrixik** [comment]
8.0.7
From directory:
```
Error: connect ETIMEDOUT 104.18.32.220:443
    at Object.exports._errnoException (util.js:1050)
    at exports._exceptionWithHostPort (util.js:1073)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097)
actions.js:47 Error: Installing failed.
    at EventEmitter.o (install-app-async.js:23)
    at emitThree (events.js:121)
    at EventEmitter.emit (events.js:197)
```
Custom app:
```
Error: connect ETIMEDOUT 35.159.8.160:443
    at Object.exports._errnoException (util.js:1050)
    at exports._exceptionWithHostPort (util.js:1073)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097)
```
Sorry for causing so many troubles.

**Comment by nyex** [comment]
@quanglam2807 just to let you know my internet connection woke up in a good mood so I managed to complete the download of electron and then installed apps with no problem. but still it had to download electron. :)

**Comment by quanglam2807** [comment]
@nyex Thanks a lot for letting me know!

@matrixik No worries! It looks like the app fails to download Electron from GitHub Releases.

**Comment by quanglam2807** [comment]
I disable resource sharing feature by default with v9.0.0. Hopefully, it will fix this issue. Can you guy test it: https://github.com/webcatalog/webcatalog/releases/tag/v9.0.0?

**Comment by nyex** [comment]
@quanglam2807 It's still trying to download electron... which fails for me because my connection is too slow :( I always get a timeout error after a while.

But then I was with 8.0.7 and even though it did download electron once, after a few days when I wanted to install a different app, it started downloading electron again, and -- well, I couldn't install anything anymore. 

(I can barely download the .deb from the releases, I have to use wget with --continue and re-do the command every 2 or 3 minutes until it finishes without a timeout. I think it's a github thing, happens with any other release file in any other github project...)

**Comment by nyex** [comment]
Ok, while I typed, my connection went and surprised me, so it finished downloading electron v1.7.10 and installation of apps worked. Hopefully it won't have to download electron again in the future?

**Comment by quanglam2807** [comment]
@nyex Hope so. I'm also working to make the app accessible via npm CLI. It'll definitely be more stable. So stay tuned.

**Comment by rjhilgefort** [comment]
This is still fails for me on `9.0.0`.

OS: Mac High Sierra 10.13.2
