### ISSUE TITLE
Amazon Spain app doesn't launch on Ubuntu 16.04

### ISSUE THREAD

**Issue by fsdias** [quanglam2807/appifier#181]
I can install the "Amazon Spain" app with no issues but when I click on it doesn't launch. I'm on Ubuntu 16.04 64 bits.

**Comment by quanglam2807** [comment]
Do other apps work for you?

**Comment by fsdias** [comment]
Yes, I have tested 10+ apps and they are all working as expected

**Comment by quanglam2807** [comment]
Strange. Can you send me the content of this file: `~/.local/share/applications/webcatalog-98559201-0206-4802-bf85-3673b96081d7.desktop`.

Additionally, you can open Terminal, type `gtk-launch webcatalog-98559201-0206-4802-bf85-3673b96081d7`. Maybe it will show you some error messages.

**Comment by fsdias** [comment]
I have no idea about what happened but it's working now. Yesterday I had deleted it and reinstall it but it still would not launch. Today it's fine. Thanks for the help and sorry to bother you.

**Comment by fsdias** [comment]
Well, it happened again. Here's the error message from the terminal

fd@fd-XPS:~$ gtk-launch webcatalog-98559201-0206-4802-bf85-3673b96081d7
fd@fd-XPS:~$ module.js:472
    throw err;
    ^

Error: Cannot find module '../dialog'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/home/fd/.config/WebCatalog/apps/98559201-0206-4802-bf85-3673b96081d7/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.get [as dialog] (/home/fd/.config/WebCatalog/apps/98559201-0206-4802-bf85-3673b96081d7/resources/electron.asar/browser/api/exports/electron.js:11:16)
    at process.<anonymous> (/home/fd/.config/WebCatalog/apps/98559201-0206-4802-bf85-3673b96081d7/resources/electron.asar/browser/init.js:54:31)
    at emitOne (events.js:96:13)
    at process.emit (events.js:191:7)
    at process._fatalException (bootstrap_node.js:308:26)

**Comment by fsdias** [comment]
This also happens with the Facebook app. Usually after closing it and restarting it shortly after.

**Comment by quanglam2807** [comment]
I think it's related to the resource-sharing mechanism I introduced after #171

**Comment by quanglam2807** [comment]
I think this's resolved with v8.0.5
